generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   1

    config:
      fields:
        name:           { label: Nom }
        groups_list:    { label: Groupe(s) }
        users_list:     { label: Utilisateur(s) }
        created_at:     { label: Création }
        updated_at:     { label: Modification }

      list:
        title: Liste des permissions
        display: [=name, description, created_at, updated_at]
       

      filter:
        display: [name]

      new:
        title: Nouvelle permission

      edit:
        title: Modification "%%name%%"

      form:
        display: [name, description, groups_list, users_list]