generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Commentaire
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              commentaire
    plural:                commentaires
    route_prefix:          commentaire
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Modération des commentaires"
        display: [ id, =pseudo,  _message, _article,  email, _date ]
      filter:  ~
      form:
        class: BackendCommentaireForm
      edit:    ~
      new:     ~
