generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ArticlesLies
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              article-lie
    plural:                articles-lies
    route_prefix:          articles_lies
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
