generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CategorieFolio
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              categoriefolio
    plural:                categoriesfolio
    route_prefix:          categorie_folio
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
