generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Article
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              article
    plural:                articles
    route_prefix:          article
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Liste des articles"
        display: [=titre, _dateFormat, _categorieTitre,  nb_lu ]
      filter:  ~
      form:
        class: BackendArticleForm
      edit:    ~
      new:     ~
