generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Categorie
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              categorienews
    plural:                categoriesnews
    route_prefix:          categorie
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Liste des catégories news"
        display: [id, =titre, description, slug]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
