generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin	
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   1

    config:
      fields:
        password_again: { label: Confirmation }
        created_at:     { label: Création }
        updated_at:     { label: Modification }
        last_login:     { label: Dernière connexion }
        groups_list:    { label: Groupe(s) }
        permissions_list: { label: Permission(s) }
        is_active:      { label: Actif ? }
        is_super_admin: { label: Super administrateur ? }

      list:
        title:   Liste des utilisateurs
        display: [=username, created_at, updated_at, last_login]

      filter:
        display: [username, groups_list]

      form:
        class: sfGuardUserAdminForm
        display:
          "NONE":                   [username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]

      edit:
        title: Modification "%%username%%"

      new:
        title: Nouvel utilisateur