generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_doctrine_route:   1

    config:
      fields:
        name:           { label: Nom }
        users_list:     { label: Utilisateur(s) }
        permissions_list: { label: Permission(s) }
        created_at:     { label: Création }
        updated_at:     { label: Modification }

      list:
        title: Liste des groupes
        display: [=name, description, created_at, updated_at]

      filter:  
        display: [name]

      edit:
        title: Modification "%%name%%"

      new:
        title: Nouveau groupe

      form:
        display: [name, description, permissions_list, users_list]
